version: "2"

services:
  voting-app:
    build: ./vote/.
    ports:
      - "5000:80"
    networks:
      back-tier:

  result-app:
    build: ./result/.
    ports:
      - "5001:80"
    networks:
      back-tier:

  worker:
    image: manomarks/worker
    networks:
      back-tier:
       aliases:
        - workers
  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      back-tier:

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      back-tier:

volumes:
  db-data:

networks:
  back-tier:
